Editor Overscroll
CodeEditApp/CodeEditTextView pull request #100
Opened 2022-12-07 11:16 UTC by yusufozgul

Related Issue:
- #63

2022-12-07 12:18 UTC, lukepistrol commented
Great work! 

One suggestion though:

- The current solution takes a fixed number of lines for the over scroll which might be more than the visible area of the text view. For example let's say the window has a height of 600pt and the over scroll line count is 70. For a font size of 13 pt this would result in a too large over scroll -> no content is visible once scrolled down all the way.

- Let's try to instead provide a double (0.0-1.0) which indicates in percent of the views visible height how large the over scroll is. This should also respect window size changes and recalculate the content inset based on that.

2022-12-07 18:01 UTC, yusufozgul commented
Thank you for review :) 
 
Yes, you are right, I made changes, also I realized a bug while changing the content inset, I should have changed contentView's bottom inset not scrollView. Otherwise after updating once, the interface does not change

2022-12-07 21:38 UTC, lukepistrol requested changes
Just a few documentation inconsistencies 

Let's also add the newly added symbols to the `Documentation.docc` catalog.
- `Sources/CodeEditTextView/Documentation.docc/CodeEditTextView.md`
- `Sources/CodeEditTextView/Documentation.docc/STTextViewController.md`

Also have a look at the failing SwiftLint rules

2022-12-07 21:38 UTC, lukepistrol commented on Sources/CodeEditTextView/CodeEditTextView.swift
> +        overScrollRatio: Binding<Double> = .constant(0.0),
please add `overScrollRatio` to the DocC comment annotation

2022-12-07 22:28 UTC, lukepistrol commented on Sources/CodeEditTextView/CodeEditTextView.swift
> +        overScrollRatio: Binding<Double> = .constant(0.0),
This still needs to be resolved

2022-12-07 22:30 UTC, lukepistrol commented on Sources/CodeEditTextView/CodeEditTextView.swift
> +        overScrollRatio: Binding<Double> = .constant(0.0),
For clarification: I meant the doc comment above the init describing all the parameters.

2022-12-08 04:15 UTC, austincondiff commented on Sources/CodeEditTextView/STTextViewController.swift
>      /// The overScrollLineCount to use for the textView over scroll
@lukepistrol Why "ratio", isn't it representing a integer value and not a ratio?

2022-12-08 04:33 UTC, austincondiff commented
This is my fault for not adding a description to the issue but I'd like to discuss how this works. I see now what @lukepistrol is suggesting. The first question is, does it make sense to allow that much flexibility?

As an example, Nova only has Small, Medium, and Large
<img width="358" alt="image" src="https://user-images.githubusercontent.com/806104/206356423-ead655e9-676a-463b-b5f1-12476c07f992.png">

VS Code only has a checkbox
<img width="461" alt="image" src="https://user-images.githubusercontent.com/806104/206356515-6222d647-3f68-4ab6-bb4d-60118e5b87c9.png">

My second question is, how are we displaying this in our Settings panel? 
If this is a percentage of editor viewport height, we should set this via a slider control
If this is a boolean, we should set this via a checkbox
And if we choose set values, we should handle it similar to Nova with a select input

2022-12-08 06:43 UTC, yusufozgul commented
@austincondiff I actually thought Xcode like (none, small, medium, large). And even Nova the same. For ide, values will be just constant percentage.
Xcode percentages: 0.25, 0.5, 0.75

2022-12-08 11:29 UTC, lukepistrol commented
@austincondiff I would either go with the way Xcode handles it (none, small, medium, large) or a slider with detents (0% - 100% in 10% steps).

A fixed number of lines becomes problematic when the window height becomes smaller than said amount. And a on-off toggle is not enough flexibility.

2022-12-08 11:34 UTC, lukepistrol commented on Sources/CodeEditTextView/STTextViewController.swift
>      /// The overScrollLineCount to use for the textView over scroll
It's representing a Double (0.0-1.0) which is a percentage of the viewport height. So it is a quantitive relation between those values.

2022-12-08 15:30 UTC, matthijseikelenboom commented
> Doesn't "amount" imply a number?

Yeah I agree. `editorOverscrollSetting` or `editorOverscrollConfig` comes to mind for me. But perhaps `editorOverscroll` is also fine.

2022-12-08 18:07 UTC, austincondiff commented
I mean, "Editor Overscroll" is what the label says, so `editorOverscroll` makes sense to me

2022-12-09 09:17 UTC, yusufozgul commented
It seems `editorOverscroll` nice for everyone

2022-12-09 14:30 UTC, austincondiff approved these changes

2022-12-09 14:52 UTC, matthijseikelenboom approved these changes

2022-12-09 18:49 UTC, lukepistrol approved these changes
LGTM 👍

2022-12-09 18:50 UTC, merged