New Feature: Compute the cursor position
CodeEditApp/CodeEditTextView pull request #134
Opened 2023-01-26 11:34 UTC by Eliulm

In essence, the line is calculated by dividing the y-position of the text segment with the cursor by the line height:
```swift 
var line = Int(textSegmentFrame.maxY / textSegmentFrame.height)
```
However, this counts the preceding line wraps as lines too. As a result, I have to count the preceding line wraps with:
```swift
textLayoutManager.enumerateTextLayoutFragments(from: textLayoutManager.documentRange.location,
                                                           options: [.ensuresLayout, .ensuresExtraLineFragment]
            ) { textLayoutFragment in

                guard let cursorTextLineFragment = textLayoutManager.textLineFragment(at: insertionPointLocation)
                else { return false }

                /// Check whether the textLayoutFragment has line wraps
                if textLayoutFragment.textLineFragments.count > 1 {
                    for lineFragment in textLayoutFragment.textLineFragments {
                        lineWrapsCount += 1
                        /// Do not count lineFragments after the lineFragment where the cursor is placed
                        if lineFragment == cursorTextLineFragment { break }
                    }

                    /// The first lineFragment will be counted as an actual line
                        lineWrapsCount -= 1
                }

                if textLayoutFragment.textLineFragments.contains(cursorTextLineFragment) {
                    return false
                }
                return true
            }
```
Unfortunately, this does scale with the line count of the file. So we might want to change that if we can come up with a better alternative in the future. As a first implementation, I think it works.

2023-01-26 12:03 UTC, lukepistrol requested changes
Just a few code style suggestions to comply with our [code style guidelines](https://github.com/CodeEditApp/CodeEdit/wiki/Code-Style#parameter-alignment)

2023-01-26 12:03 UTC, lukepistrol commented on Sources/CodeEditTextView/STTextViewController.swift
> +            ) { textLayoutFragment in
Please try to use multi-line indents for arguments like this:

```suggestion
            textLayoutManager.enumerateTextLayoutFragments(
                from: textLayoutManager.documentRange.location,
                options: [.ensuresLayout, .ensuresExtraLineFragment]
            ) { textLayoutFragment in
```

Reference: https://github.com/CodeEditApp/CodeEdit/wiki/Code-Style#parameter-alignment

2023-01-26 12:03 UTC, lukepistrol commented on Sources/CodeEditTextView/STTextViewController.swift
> +            ) { _, textSegmentFrame, _, _ -> Bool
Please try to use multi-line indents for arguments like this:

```suggestion
            textLayoutManager.enumerateTextSegments(
                in: NSTextRange(location: insertionPointLocation),
                type: .standard,
                options: [.rangeNotRequired, .upstreamAffinity]
            ) { _, textSegmentFrame, _, _ -> Bool
```

Reference: https://github.com/CodeEditApp/CodeEdit/wiki/Code-Style#parameter-alignment

2023-01-26 18:00 UTC, thecoolwinter commented
This will break when #131 is fixed. Instead of enumerating the entire string, could we use `insertionPointLocation` to get the line and column directly? We already compute the visible location, so we'd get the line like: `insertionPointLocation.nsRange(...).location - visibleRange.location` and then compute the column by walking backwards from the `insertionPointLocation` until we hit a `\n`. A similar approach could be used in `setCursorPosition`.

2023-01-26 18:05 UTC, thecoolwinter requested changes

2023-01-26 18:05 UTC, thecoolwinter commented on Sources/CodeEditTextView/CodeEditTextView.swift
> +        cursorPosition: Binding<(Int, Int)>,
Could you add this to the DocC comment above? I don't know why it's not already there.

2023-01-26 18:05 UTC, thecoolwinter commented on Sources/CodeEditTextView/STTextViewController.swift
> +            guard let textLayoutManager = self?.textView.textLayoutManager else { return }
This guard statement should be in the method itself so we can see quickly that it will fail if there is no layout manager.

2023-01-26 18:05 UTC, thecoolwinter commented on Sources/CodeEditTextView/STTextViewController.swift
> +            // TODO: Find a more performant approach, that does not scale with line count
See comment on PR about performance

2023-01-27 19:19 UTC, thecoolwinter commented
No, don't discard it it can stay open

2023-02-16 03:34 UTC, thecoolwinter commented
Now that the viewport issue is fixed, it looks like there’s a better way to get the number of lines at the beginning of the visible area.

https://github.com/krzyzanowskim/STTextView/blob/7c378dca8e15902f7762d13bc1e33134a7729ed8/Sources/STTextView/STLineNumberRulerView.swift#L146

Let me know if you’re still willing to work on this, and thank you for being so patient while we got everything else finished.

2023-02-16 08:37 UTC, Eliulm commented
Not a problem, I was occupied with exams anyway so I did not do too much there. I will work on this in the coming days.

2023-02-19 21:09 UTC, Eliulm commented
@thecoolwinter So I just reimplemented `updateCursorPosition()` and it works much better now. However, I am having issues when the last empty line is edited since it is not immediately converted into a new `textLineFragment`. As a result, the line and column values become out of sync, until the cursor is moved one back:

https://user-images.githubusercontent.com/82230675/219975291-962d4f49-acda-41d6-aeb5-1d9e77ae1cd6.mov

I will see what I can do about it, but I am a bit clueless right now.

2023-02-20 15:15 UTC, thecoolwinter commented
Oh that's a weird problem. Good catch though. I'll do some investigating too

2023-03-05 14:05 UTC, Eliulm commented
@thecoolwinter I have found a workaround for the last line. I had to add a bit more code to get it to work and swiftlint is giving me function_boy_length errors now. Should I ignore it or move the cursor-specific code to a separate new folder?

2023-03-15 16:58 UTC, austincondiff commented
What is the status of this? It has been open for over a month now and I want to make sure we aren't blocked.

2023-03-15 18:02 UTC, Eliulm commented
It is working as expected. I just need to know, whether I should allocate all the cursor logic to a separate file/folder since I am getting SwiftLint function_boy_length errors now.

2023-03-15 18:43 UTC, thecoolwinter commented
So sorry I missed the comments on this. You’ll have to move it to a new file. You can make a `Controller` folder and move `STTextViewController.swift` into there, and make a new `STTextViewController+Cursor.swift` file for the cursor additions.

2023-03-15 19:10 UTC, Eliulm commented
No Problem, I will do it shortly.

2023-03-15 20:50 UTC, Eliulm commented
@thecoolwinter Alright, I moved it over.

2023-03-15 20:54 UTC, thecoolwinter approved these changes
Looks good! Thanks for all the work on this!

2023-03-15 23:23 UTC, lukepistrol approved these changes

2023-03-15 23:23 UTC, merged