Add Injected Language Support
CodeEditApp/CodeEditTextView pull request #150
Opened 2023-02-28 21:22 UTC by thecoolwinter

# Description

> This is still a draft. There are a couple things that still need to be resolved. Specifically:
> - Incremental edits with injected languages.
> - Avoiding re-parsing the file for each injected language, each query.

This PR adds support for injected languages using tree-sitter as described in #16 and in the [tree-sitter documentation](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection). Languages can contain _injected_ languages which are described in a language's `injections.scm` file. Some examples of injected languages are:
- HTML contains CSS and Javascript in `style` and `script` tags
- Javascript contains Regex literals
- PHP contains HTML between the `<php` tags
- C++ can contain rawstring literals of arbitrary languages

# Details

This is largely a rework of the `TreeSitterClient` class. It adds a `languages` dictionary to store arbitrary languages and eliminate copies of each injected language. It also adds the `queryInjectedLanguages` method for finding ranges of injected languages given a language. This method is designed to be called recursively, so Javascript embedded in HTML can still inject Regex.

The way trees are modified and parsed has changed as well, now that there is no instance-wide `tree` and `parser` variables. Instead methods like `createTree` have been modified to return values instead of setting `self`-wide variables.

# Related Issues

- Closes #16 

# Screenshots

Before, other languages were detected but parsed and highlighted as normal text.
<img width="1104" alt="Screenshot 2023-02-28 at 3 08 52 PM" src="https://user-images.githubusercontent.com/35942988/221980502-3aa61b6a-136a-43b9-a545-8fd835945002.png">

With Injected languages:

https://user-images.githubusercontent.com/35942988/221979730-49929661-9d69-4da7-ad5b-7284f916857a.mov

2023-03-10 08:38 UTC, lukepistrol commented
Is this still WIP?

2023-03-21 17:48 UTC, thecoolwinter commented
> Is this still WIP?

Yeah it is. There are still some glaring issues right now that I thought would be trivial to fix but are ending up being trickier than expected.

2023-03-24 20:56 UTC, lukepistrol requested changes
Just a couple of code style considerations about function parameter indentation. I provided fixes for most of them.

Refs: [Code Style](https://github.com/CodeEditApp/CodeEdit/wiki/Code-Style#parameter-alignment)

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/Extensions/NSRange+/NSRange+TSRange.swift
> +                       bytes: (UInt32(self.location) * 2)..<(UInt32(self.location + self.length) * 2))
### [CodeStyle]: 

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
        return TSRange(
            points: .zero..<(.zero),
            bytes: (UInt32(self.location) * 2)..<(UInt32(self.location + self.length) * 2)
        )
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient+Edit.swift
> +                               readBlock: @escaping Parser.ReadBlock) -> [NSRange] {
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
    func findChangedByteRanges(
        textView: HighlighterTextView,
        edit: InputEdit,
        layer: LanguageLayer,
        readBlock: @escaping Parser.ReadBlock
    ) -> [NSRange] {
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient+Edit.swift
> +                                                   readBlock: readBlock)
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
        let (oldTree, newTree) = calculateNewState(
            tree: layer.tree,
            parser: layer.parser,
            edit: edit,
            readBlock: readBlock
        )
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient+Edit.swift
> +                                    readBlock: @escaping Parser.ReadBlock) -> (Tree?, Tree?) {
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
    internal func calculateNewState(
        tree: Tree?,
        parser: Parser,
        edit: InputEdit,
        readBlock: @escaping Parser.ReadBlock
    ) -> (Tree?, Tree?) {
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient+Edit.swift
> +                                               readBlock: @escaping Parser.ReadBlock) -> IndexSet {
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
    internal func updateInjectedLanguageLayers(
        textView: HighlighterTextView,
        layer: LanguageLayer,
        layerSet: inout Set<LanguageLayer>,
        touchedLayers: inout Set<LanguageLayer>,
        readBlock: @escaping Parser.ReadBlock
    ) -> IndexSet {
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient+Highlight.swift
> +                                       range: NSRange) -> [HighlightRange] {
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
    internal func queryLayerHighlights(
        layer: LanguageLayer,
        textView: HighlighterTextView,
        range: NSRange
    ) -> [HighlightRange] {
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient+LanguageLayer.swift
> +             ranges: [NSRange]) {
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
        init(
            id: TreeSitterLanguage,
            parser: Parser,
            supportsInjections: Bool,
            tree: Tree? = nil,
            languageQuery: Query? = nil,
            ranges: [NSRange]
        ) {
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient.swift
> +                          ranges: [])
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
            LanguageLayer(
                id: codeLanguage.id,
                parser: Parser(),
                supportsInjections: codeLanguage.additionalHighlights?.contains("injections") ?? false,
                tree: nil,
                languageQuery: TreeSitterModel.shared.query(for: codeLanguage.id),
                ranges: []
            )
```

2023-03-24 20:56 UTC, lukepistrol commented on Sources/CodeEditTextView/TreeSitter/TreeSitterClient.swift
> +                                                               range: NSRange(range)))
### [CodeStyle]:

Maybe try to not indent to much. In the `CodeEdit` repo this is not allowed by SwiftLint. We should keep it consistent.

```suggestion
            highlights.append(contentsOf: queryLayerHighlights(
                layer: layers[0],
                textView: textView,
                range: NSRange(range)
            ))
```

2023-03-24 21:10 UTC, 0xWDG submitted a review, later dismissed

2023-03-24 21:10 UTC, 0xWDG commented on Sources/CodeEditTextView/Extensions/NSRange+/NSRange+Comparable.swift
> +//  File.swift
Maybe update the file name comment

2023-03-24 21:26 UTC, lukepistrol approved these changes
LGTM 👍

2023-03-24 22:11 UTC, austincondiff approved these changes
This is really great work @thecoolwinter! 👏

2023-03-24 22:33 UTC, lukepistrol commented
@thecoolwinter Are there any breaking changes regarding the public API? Need to know when releasing a new version.

2023-03-24 22:35 UTC, thecoolwinter commented
> @thecoolwinter Are there any breaking changes regarding the public API? Need to know when releasing a new version.

Yes, there's an additional method on `HighlightProvider` which external highlight providers will have to implement when updating.

2023-03-24 23:35 UTC, merged