Custom Text View
CodeEditApp/CodeEditTextView pull request #211
Opened 2023-09-03 23:07 UTC by thecoolwinter

### Description

Replaces `STTextView` with a custom TextView implementation. Creates a new `TextView` and `TextViewController` classes that manage rendering text, handling text input, and keybinds. `TextViewController` replaces the `STTextViewController` class, connecting existing TextFormation classes, syntax highlighting, and other existing text view extensions.

### Related Issues

* #208 

### Checklist

TextView TODOs:
- [X] load text
- [X] render text
- [X] scroll
- [X] wrap text
- [X] resize
- [x] syntax highlighting
- [x] cursor
- [ ] edit text
    - [x] isEditable
    - [x] Insert
    - [ ] Delete
        - [x] Delete line
        - [x] Delete word
        - [x] Delete character
        - [ ] Delete across lines
    - [x] Paste
    - [ ] [Marked Text](https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/TextEditing/TextEditing.html#//apple_ref/doc/uid/TP40009459-CH3-SW26)
- [x] Line Numbers
- [ ] Select text
    - [ ] Copy
- [ ] Multiple cursors
- [ ] Keyboard navigation
    - [ ] Arrow keys
    - [ ] Command & control arrow keys
    - [ ] Page up and down
- [ ] Tab widths & indents
- [ ] Live parameter updating
- [ ] Undo/redo
- [ ] Sync system appearance
- [ ] Highlight brackets
- [ ] TextFormation integration
- [ ] MacOS Sonoma cursor 
- [ ] Update text (from SwiftUI Binding)
- [ ] Non-scrollable view
    - [ ] SwiftUI Version
    - [ ] AppKit Version
- [ ] Accessibility

--
- [ ] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [ ] The issues this PR addresses are related to each other
- [ ] My changes generate no new warnings
- [ ] My code builds and runs on my machine
- [ ] My changes are all related to the related issue above
- [ ] I documented my code

### Screenshots

`// TODO`

2023-11-08 22:37 UTC, 0xWDG approved these changes
Nice

2023-11-17 07:58 UTC, matthijseikelenboom submitted a review, later dismissed
One quick note, some functions are implicitly `internal` and others are explicitly marked as `internal`. Is there any reason for that or is it just what it is

2023-11-18 14:48 UTC, thecoolwinter commented on Sources/CodeEditInputView/Extensions/NSTextStorage+getLine.swift
> +    public func getNextLine(startingAt location: Int) -> NSRange? {
Ah this is marked `public` because I had it in a shared target because it was used in both packages. I'll mark it private.

2023-11-18 14:57 UTC, thecoolwinter commented
@matthijseikelenboom I tend to add `internal` for myself for extra verbosity when designing an API. I've removed them since they're unnecessary.

2023-11-18 15:15 UTC, thecoolwinter commented
This is finally ready for some review!

2023-11-21 13:29 UTC, matthijseikelenboom submitted a review, later dismissed
Only comment I would have is that it'd be nice to have more tests, but that's all

2023-12-07 20:11 UTC, 0xWDG requested changes
Looks good, I have 2 notes.
1) see requested change, this header filename isn't right.

2) there is no consistency in the header docs
In some files `CodeEditTextView` is in the header docs, in others it isn't, this is not breaking but looks a bit weird to me.

```swift
 //
 //  FILENAME.swift
 //  
 //
 //  Created by Khan Winter on 11/14/23.
 //
```

And in others
```swift
 //
 //  FILENAME.swift
 //  CodeEditTextView
 //
 //  Created by Khan Winter on 11/14/23.
 //
```

2023-12-09 17:01 UTC, austincondiff approved these changes

2023-12-09 17:01 UTC, matthijseikelenboom approved these changes

2023-12-09 17:09 UTC, merged