✨ Emphasis API for Highlighting Text Ranges
CodeEditApp/CodeEditTextView pull request #62
Opened 2024-11-28 11:23 UTC by tom-ludwig

### Description
This PR introduces the Emphasis API to highlight specific text ranges within a TextView. This functionality can be used in various scenarios, such as highlighting search results, emphasizing code symbols, or highlighting the code symbol that the mouse is hovering over.
This PR only introduces the Emphasis API and does not include any search functionality or text-range validation (e.g., checking if an already emphasized range has changed).

> [!NOTE]
> To test the UI changes, you will likely need to use CESE and add CETE as a local package.
To experiment with the highlighting, add the following snippet to `TextView+KeyDown` at line `13` and change the ranges accordingly:
```swift
        let rangesToHighlight = [
            NSRange(location: 562, length: 7),
            NSRange(location: 651, length: 7),
            NSRange(location: 724, length: 7),
        ]

        if event.keyCode == kVK_F1 {
            emphasizeAPI?.emphasizeRanges(ranges: rangesToHighlight, activeIndex: 0)
            return
        }

        if event.keyCode == kVK_F2 {
            emphasizeAPI?.highlightNext()
            return
        }
        if event.keyCode == kVK_F3 {
            emphasizeAPI?.highlightPrevious()
            return
        }
        if event.keyCode == kVK_F4 {
            emphasizeAPI?.removeEmphasizeLayers()
            return
        }
```

### Related Issues

* closes #61 
* #1 

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### Screenshots

https://github.com/user-attachments/assets/30327976-f2cc-42d8-94a4-ee8f4d6e076c

Multiline:
<img width="286" alt="Screenshot 2024-11-28 at 12 12 54 PM" src="https://github.com/user-attachments/assets/2ad9bcf8-3660-4879-adf7-6b52f1d1ee84">

<img width="251" alt="Screenshot 2024-11-28 at 12 13 10 PM" src="https://github.com/user-attachments/assets/4d3bfe89-3020-4137-848d-21211ea3f8ec">

2024-12-05 16:17 UTC, thecoolwinter requested changes
Just a spelling error and a file placement suggestion. That smooth path function is beautiful, awesome stuff.

2024-12-05 16:17 UTC, thecoolwinter commented on Sources/CodeEditTextView/TextView/TextView+EmphasizeAPI.swift
Since this is a discrete class from `TextView`, could we move it to it's own folder and it's own file? I think the `TextView+` should be reserved for extensions.

2024-12-05 22:26 UTC, austincondiff commented
Excellent work @tom-ludwig! It looks really good. Just a small detail—the animation looks a little off. Instead of scaling it, it seems to be translated from below and to the right. Can we fix this?

2024-12-08 10:48 UTC, tom-ludwig commented on Sources/CodeEditTextView/TextView/TextView+EmphasizeAPI.swift
Oops, I forgot to rename it. At first, I thought a few helper functions in TextView would do the trick 😅

2024-12-08 10:50 UTC, tom-ludwig commented
@austincondiff Yeah, it’s not what Xcode is using, but honestly, I’m not really a fan of Xcode’s approach. I’ll experiment with the animation to come up with something better.

2024-12-16 04:26 UTC, austincondiff commented
Xcodes approach is a macOS standard found in many other apps. I’d like to first start with it and if we want to, later on adjust as needed.

2024-12-23 17:16 UTC, thecoolwinter approved these changes

2024-12-28 13:44 UTC, austincondiff approved these changes

2024-12-28 14:56 UTC, merged